const NavigationRouteNames = {
  SPLASH_SCREEN: 'splash_screen',
  GETTING_STARTED: 'getting_started',
  LOGIN: 'login',
  ENTER_PASSWORD: 'enter_password',
  OTP_VERIFICATION: 'otp_verification',
  SET_PASSWORD: 'set_password',
  REGISTER: 'register',
  USER_TYPE_SELECTOR: 'user_type_selector',
  REFER_EARN: 'refer_and_earn',
  PYTN_LISTING: 'pytn_listing',
  PYTN_HISTORY: 'pytn_history',
  PYTN_ADD: 'pytn_add',
  PYTN_DETAILS: 'pytn_details',
  ONLINE_CLASS: 'online_class1',

  WEB_VIEW: 'web_view',
  NOTIFICATIONS: 'notifications',
  SEND_FEEDBACK: 'send_feedback',
  ABOUT_US: 'about_us',
  CUSTOMER_CARE: 'customer_care',
  ADDRESS: 'address',
  ADD_EDIT_ADDRESS: 'add_edit_address',
  ADDRESS_MAP_VIEW: 'address_map_view',
  EDUCATION: 'education',
  ADD_EDIT_EDUCATION: 'add_edit_education',

  PERSONAL_DETAILS: 'personal_details',
  EXPERIENCE: 'experience',
  ADD_EDIT_EXPERIENCE: 'add_edit_experience',
  BANK_DETAILS: 'bank_details',
  ADD_EDIT_BANK_DETAILS: 'add_edit_bank_details',

  AWARD_LISTING: 'awards_listing',
  ADD_EDIT_AWARD_DETAILS: 'add_edit_award_details',
  BUSINESS_DETAILS: 'add_edit_bank_details',
  RATINGS_REVIEWS: 'ratings_reviews',
  UPDATE_VERSION: 'update_version',
  UNDER_MAINTAINANCE: 'under_maintainance',
  OTP_CHANGE_PASSWORD: 'otp_change_password',
  CHANGE_PASSWORD: 'change_password',
  MONTH_CALENDAR_VIEW: 'month_calendar_view',
  STUDENT: {
    ON_BOARDING: 'student_on_boarding',
    MY_STUDY_AREAS: 'my_study_areas',
    STUDY_AREA: 'student_study_area',
    BOARD: 'student_board',
    CLASS: 'student_class',
    DASHBOARD: 'student_dashboard',
    CALENDAR: 'student_calendar',
    CLASSES: 'student_classes',
    TUTOR: 'student_tutor',
    PROFILE: 'student_profile',
    COMPARE_TUTORS: 'compare_tutors',
    TUTOR_DETAILS: 'tutor_details',
    MY_CART: 'my_cart',
    PAYMENT_METHOD: 'payment_method',
    BOOKING_CONFIRMED: 'booking_confirmed',
    PAYMENT_RECEIVED: 'payment_received',
    MY_CLASSES: 'my_classes',
    SCHEDULE_CLASS: 'schedule_class',
    SCHEDULED_CLASS_DETAILS: 'scheduled_class_details',
    CANCEL_REASON: 'cancel_reason',
    ONLINE_CLASS: 'online_class',
    RATE_AND_REVIEW: 'rate and review',
    DETAILED_RATING: 'detailed rating',
    COMPARE_MODAL: 'compare_modal',
    FAVOURITE_TUTOR: 'favourite_tutor',
    BOOKING_DETAILS: 'booking_details',
    VIEW_BOOKING_DETAILS: 'view_booking_details',
    REFUND: 'refund',
    ORDER_DETAILS: 'order_details',
    PARENTS_LIST: 'parents',
    ADD_EDIT_PARENTS: 'add_edit_parents',
  },
  TUTOR: {
    ON_BOARDING: 'tutor_on_boarding',
    DASHBOARD: 'tutor_dashboard',
    CANCEL_REASON: 'cancel_reason',
    ONLINE_CLASS: 'online_class',
    WELCOME_SCREEN: 'welcome_screen',
    CERTIFICATE_STEPS: 'certificate_steps',
    CERTIFICATION_COMPLETED_VIEW: 'certification_completed_view',
    SUBJECTS_LIST: 'subjects_list',
    SUBJECT_SELECTION: 'subject_selection',
    PRICE_MATRIX: 'price_matrix',
    VIEW_SCHEDULE: 'view_schedule',
    UPDATE_SCHEDULE: 'update_schedule',
    STUDENT_REQUESTS: 'student_requests',
    SCHEDULE_YOUR_INTERVIEW: 'schedule_your_interview',
    PT_START_SCREEN: 'pt_start_screen',
    PROFICIENCY_TEST: 'proficiency_test',
    COMPLETE_PROFILE: 'complete_profile',
    INTERVIEW_AND_DOCUMENTS: 'interview_and_documents',
    UPLOAD_DOCUMENTS: 'upload_documents',
    BACKGROUND_CHECK: 'background_check',
    VERIFICATION: 'verification',
    BUSINESS_DETAILS: 'business_details',
    ADD_EDIT_BUSINESS_DETAILS: 'add_edit_business_details',
    DOCUMENT_LISTING: 'document_listing',
    ADD_DATA: 'add_data',
    STUDENT_LISTING: 'student_listing',
    STUDENT_DETAILS: 'student_details',
  },
};

export default NavigationRouteNames;
