const NavigationRouteNames = {
  SPLASH_SCREEN: 'splash_screen',
  GETTING_STARTED: 'getting_started',
  LOGIN: 'login',
  ENTER_PASSWORD: 'enter_password',
  OTP_VERIFICATION: 'otp_verification',
  SET_PASSWORD: 'set_password',
  REGISTER: 'register',
  USER_TYPE_SELECTOR: 'user_type_selector',
  REFER_EARN: 'refer_and_earn',
  POST_TUTION_NEEDS: 'post_your_tution_needs',
  POST_TUTION_NEED_DETAILS: 'post_your_tution_need_details',
  WEB_VIEW_PAGES: 'web_view_pages',
  TUTION_NEEDS_LISTING: 'tution_needs_listing',
  TUTION_NEEDS_HISTORY: 'tution_needs_history',
  ONLINE_CLASS: 'online_class1',

  WEB_VIEW: 'web_view',
  NOTIFICATIONS: 'notifications',

  STUDENT: {
    ON_BOARDING: 'student_on_boarding',
    STUDY_AREA: 'student_study_area',
    BOARD: 'student_board',
    CLASS: 'student_class',
    DASHBOARD: 'student_dashboard',
    CALENDAR: 'student_calendar',
    CLASSES: 'student_classes',
    TUTOR: 'student_tutor',
    PROFILE: 'student_profile',
    PERSONAL_DETAILS: 'personal_details',
    COMPARE_TUTORS: 'compare_tutors',
    TUTOR_DETAILS: 'tutor_details',
    MY_CART: 'my_cart',
    PAYMENT_METHOD: 'payment_method',
    BOOKING_CONFIRMED: 'booking_confirmed',
    PAYMENT_RECEIVED: 'payment_received',
    MY_CLASSES: 'my_classes',
    SCHEDULE_CLASS: 'schedule_class',
    SCHEDULED_CLASS_DETAILS: 'scheduled_class_details',
    CANCEL_REASON: 'cancel_reason',
    ONLINE_CLASS: 'online_class',
    RATE_AND_REVIEW: 'rate and review',
    DETAILED_RATING: 'detailed rating',
    COMPARE_MODAL: 'compare_modal',
    FAVOURITE_TUTOR: 'favourite_tutor',
    NOTIFICATIONS: 'notifications',
  },
  TUTOR: {
    ON_BOARDING: 'tutor_on_boarding',
    DASHBOARD: 'tutor_dashboard',
    CANCEL_REASON: 'cancel_reason',
    ONLINE_CLASS: 'online_class',
    CERTIFICATION_COMPLETED_VIEW: 'certification_completed_view',
    SUBJECTS_LIST: 'subjects_list',
    PRICE_MATRIX: 'price_matrix',
    VIEW_SCHEDULE: 'view_schedule',
    UPDATE_SCHEDULE: 'update_schedule',
    STUDENT_REQUESTS: 'student_requests',
  },
};

export default NavigationRouteNames;
