const NavigationRouteNames = {
  SPLASH_SCREEN: 'splash_screen',
  GETTING_STARTED: 'getting_started',
  LOGIN: 'login',
  ENTER_PASSWORD: 'enter_password',
  OTP_VERIFICATION: 'otp_verification',
  SET_PASSWORD: 'set_password',
  REGISTER: 'register',
  USER_TYPE_SELECTOR: 'user_type_selector',

  STUDENT: {
    ON_BOARDING: 'student_on_boarding',
    STUDY_AREA: 'student_study_area',
    BOARD: 'student_board',
    CLASS: 'student_class',
    DASHBOARD: 'student_dashboard',
    CALENDAR: 'student_calendar',
    CLASSES: 'student_classes',
    TUTOR: 'student_tutor',
    PROFILE: 'student_profile',
    PERSONAL_DETAILS: 'personal_details',
    COMPARE_TUTORS: 'compare_tutors',
    TUTOR_DETAILS: 'tutor_details',
    SELECT_CLASS_MODE: 'select_class_mode',
    MY_CART: 'my_cart',
    PAYMENT_METHOD: 'payment_method',
    BOOKING_CONFIRMED: 'booking_confirmed',
    PAYMENT_RECEIVED: 'payment_received',
    MY_CLASSES: 'my_classes',
    SCHEDULE_CLASS: 'schedule_class',
    SCHEDULED_CLASS_DETAILS: 'scheduled_class_details',
    CANCEL_REASON: 'cancel_reason',
    ONLINE_CLASS: 'online_class',
  },
  TUTOR: {
    ON_BOARDING: 'tutor_on_boarding',
    DASHBOARD: 'tutor_dashboard',
  },
};

export default NavigationRouteNames;
