import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import { Colors } from '../../../theme';
import { RfH, RfW } from '../../../utils/helpers';
import Fonts from '../../../theme/fonts';
import { STANDARD_SCREEN_SIZE } from '../../../utils/constants';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: RfW(16),
    paddingVertical: RfH(16),
  },
  childContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    paddingHorizontal: RfW(16),
  },
  bottomBarView: {
    width: '90%',
    height: 0.5,
    alignSelf: 'center',
    borderColor: Colors.lightGrey,
    borderWidth: 1.5,
  },
  nameTextStyle: {
    fontSize: RFValue(16, STANDARD_SCREEN_SIZE),
    color: Colors.black,
    fontFamily: Fonts.semiBold,
    lineHeight: 21,
    letterSpacing: 0.32,
  },
  idTextStyle: {
    fontSize: RFValue(14, STANDARD_SCREEN_SIZE),
    color: Colors.darkGrey,
    lineHeight: 19,
    letterSpacing: 0.28,
  },
  subscreenheadingView: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: RFValue(16, STANDARD_SCREEN_SIZE),
    paddingVertical:RFValue(8,STANDARD_SCREEN_SIZE)
  },
  subscreenheadingView_Two: {
    flex: 0.1,

    flexDirection: 'row',
    padding: RFValue(16, STANDARD_SCREEN_SIZE),
  },
  subscreenheadingText: {
    fontSize: RFValue(22, STANDARD_SCREEN_SIZE),
    color: Colors.black,
    fontFamily: Fonts.bold,
    justifyContent: 'center',
    alignSelf: 'flex-start',
  },
  subscreenviewAll: {
    flex: 1,
  },
  textviewAll: {
    fontSize: RFValue(14, STANDARD_SCREEN_SIZE),
    color: Colors.secondaryText,
    right: 0,
    position: 'absolute',
    fontFamily: Fonts.regular,
    textAlign: 'center',
  },
  filterContainerView: {
    flexDirection: 'row',
  },
  filterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: RfW(8),
    paddingVertical: RfH(10),
  },
  filterText: {
    fontSize: RFValue(15, STANDARD_SCREEN_SIZE),
    color: Colors.darkGrey,
    marginLeft: RfW(8),
    fontFamily: Fonts.semiBold,
  },
  subjectText: {
    fontSize: RFValue(15, STANDARD_SCREEN_SIZE),
    color: Colors.darkGrey,
    marginLeft: RfW(8),
    fontFamily: Fonts.semiBold,
    textTransform: 'capitalize',
  },
  topView: {
    // height: RfH(98),
    backgroundColor: Colors.lightPurple,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? RfH(44) : RfH(22),
  },
  headerComponent: {
    // height: RfH(70),
    paddingVertical: RfH(15),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: RfW(16),
  },
  stickyHeader: {
    // height: RfH(98),
    // marginTop: RfH(88),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: RfW(16),
    backgroundColor: Colors.lightPurple,
  },
  bookIcon: {
    height: RfH(30),
    width: RfH(30),
  },
  switchView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: 54,
  },
  switchText: {
    fontSize: RFValue(16, STANDARD_SCREEN_SIZE),
    fontFamily: 'SegoeUI-Semibold',
  },
  subjectTitle: {
    color: Colors.primaryText,
    fontSize: RFValue(20, STANDARD_SCREEN_SIZE),
    fontFamily: Fonts.semiBold,
  },
  classText: {
    color: Colors.darkGrey,
    fontSize: RFValue(15, STANDARD_SCREEN_SIZE),
  },
  filterParentView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: Colors.borderColor,
    borderBottomWidth: 0.5,
    paddingLeft: RfW(16),
    backgroundColor: Colors.white,
    // height: RfH(44),
  },
  filterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: RfW(16),
    paddingVertical: RfH(10),
  },
  tutorCountText: {
    fontSize: RFValue(15, STANDARD_SCREEN_SIZE),
    color: Colors.primaryText,
    // marginLeft: RfW(8),
  },
  filterText: {
    fontSize: RFValue(15, STANDARD_SCREEN_SIZE),
    color: Colors.darkGrey,
    letterSpacing: 0.28,
    lineHeight: RfH(19),
    marginLeft: RfW(5),
    fontFamily: Fonts.semiBold,
  },
  horizontalLine: {
    width: '100%',
    borderWidth: 0.2,
    opacity: 0.15,
    borderColor: Colors.darkGrey,
    height: RfH(1),
    marginTop: RfH(4),
  },
  listItemParent: {
    // borderRadius: RfH(8),
    marginBottom: RfH(24),
  },
  userIconParent: {
    // flex: 0.3,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userIcon: {
    height: RfH(90),
    width: RfW(80),
    borderRadius: RfH(8),
  },
  tutorName: {
    fontSize: RFValue(17, STANDARD_SCREEN_SIZE),
    color: Colors.primaryText,
    fontFamily: Fonts.semiBold,
  },
  tutorDetails: {
    fontSize: RFValue(15, STANDARD_SCREEN_SIZE),
    color: Colors.secondaryText,
    marginTop: RfH(2),
  },

  classMeta: {
    fontSize: RFValue(10, STANDARD_SCREEN_SIZE),
    color: Colors.secondaryText,
    marginTop: RfH(2),
  },

  chargeText: {
    color: Colors.black,
    fontSize: RFValue(15, STANDARD_SCREEN_SIZE),
    // fontFamily: Fonts.semiBold,
    // marginLeft: RfW(4),
  },
  iconsView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
  },
  backButton: {
    alignSelf: 'flex-start',
    // marginLeft: RfW(8),
    marginTop: RfH(24),
  },
  filterPopupParentView: {
    flex: 1,
    backgroundColor: 'transparent',
    flexDirection: 'column',
  },
  transparentTopView: {
    backgroundColor: Colors.black,
    opacity: 0.5,
    flex: 1,
  },
  bottomViewParent: {
    bottom: 0,
    left: 0,
    right: 0,
    position: 'absolute',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    backgroundColor: Colors.white,
  },
  popupHeaderView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: Colors.darkGrey,
    borderBottomWidth: RfW(0.3),
    height: RfH(56),
  },
  filterContentView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    // marginBottom: RfH(40),
  },
  filterItemView: {
    flex: 0.4,
    // borderRightColor: Colors.darkGrey,
    // borderRightWidth: 0.5,
    paddingBottom: RfH(80),
  },
  filterButtonParent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginBottom: RfH(40),
    marginHorizontal: RfW(16),
  },
  buttonText: {
    fontSize: RFValue(16, STANDARD_SCREEN_SIZE),
    fontFamily: 'SegoeUI-Semibold',
  },
  borderButton: {
    flex: 0.5,
    borderColor: Colors.brandBlue2,
    justifyContent: 'center',
    marginRight: RfW(4),
  },
  solidButton: {
    flex: 0.5,
    backgroundColor: Colors.brandBlue2,
    marginLeft: RfW(4),
  },
  activeFilterItem: {
    height: RfH(52),
    backgroundColor: Colors.white,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  disableFilterItem: {
    height: RfH(52),
    backgroundColor: Colors.lightGrey,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  indicatorView: {
    width: RfW(4),
    height: RfH(52),
  },
  filterButton: {
    borderWidth: 0.5,
    borderColor: Colors.primaryText,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // padding: RfH(8),
    // height: RfH(28),
    marginVertical: RfH(4),
    marginRight: RfW(8),
    paddingVertical: RfW(4),
    paddingHorizontal: RfW(8),
    borderRadius: RfW(4),
  },
  compareTutorName: {
    marginTop: RfH(16),
    alignSelf: 'center',
    fontFamily: Fonts.semiBold,
    fontSize: RFValue(17, STANDARD_SCREEN_SIZE),
  },
  informationParentMargin: {
    paddingHorizontal: RfW(16),
    marginTop: RfH(30),
  },
  infoCategoryText: {
    marginTop: RfH(8),
    alignSelf: 'center',
    color: Colors.black,
  },
  ratingText: {
    fontSize: RFValue(10, STANDARD_SCREEN_SIZE),
    color: Colors.darkGrey,
  },
  qualificationItemText: {
    flex: 0.5,
    color: Colors.darkGrey,
    marginTop: RfH(8),
  },
  typeItemText: {
    color: Colors.darkGrey,
    alignSelf: 'center',
    marginLeft: RfW(8),
  },
  crossIcon: {
    alignSelf: 'flex-end',
    borderColor: Colors.darkGrey,
    // borderWidth: 1,
    borderRadius: 9,
  },
  topViewAfterScroll: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: Colors.lightPurple,
    paddingTop: RfH(8),
  },
  appliedFilterText: {
    fontSize: RFValue(13, STANDARD_SCREEN_SIZE),
    color: Colors.darkGrey,
  },
  itemView: {
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    borderColor: Colors.darkGrey,
  },
  buttonParentView: {
    alignSelf: 'center',
    marginTop: RfH(30),
    marginBottom: RfH(34),
  },
  bookingSelectorParent: {
    borderRadius: 4,
    width: RfW(80),
    height: RfH(36),
    borderWidth: 1,
    borderColor: Colors.brandBlue2,
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  tutorIcon: {
    alignSelf: 'center',
    marginTop: RfH(48),
    borderRadius: RfW(16),
  },
  classTableText: {
    flex: 0.25,
    fontSize: RFValue(16, STANDARD_SCREEN_SIZE),
    color: Colors.darkGrey,
    textAlign: 'center',
  },
  fabActionParent: {
    bottom: RfH(84),
    right: RfW(16),
    position: 'absolute',
    height: RfH(56),
    width: RfH(56),
    borderRadius: 28,
    backgroundColor: Colors.orange,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartText: {
    marginTop: RfH(-27),
    marginLeft: RfW(8),
    alignSelf: 'center',
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: RFValue(12, STANDARD_SCREEN_SIZE),
  },
  tutorListContainer: {
    paddingHorizontal: RfH(16),
    marginTop: RfH(20),
    marginBottom: RfH(34),
  },
  footerLoadMore: {
    marginTop: RfH(10),
    paddingVertical: RfH(12),
    alignItems: 'center',
    marginHorizontal: RfW(30),
    borderWidth: 1,
    borderRadius: RfH(10),
  },
});
