/* eslint-disable no-dupe-keys */
/* eslint-disable global-require */
const Images = {
  onBoardingFirst: require('../assets/images/tutorDetail5.png'),
  onBoardingSecond: require('../assets/images/onboarding2.png'),
  onBoardingThird: require('../assets/images/onboarding3.png'),
  splashScreen: require('../assets/images/splash_image.png'),
  chevronRight: require('../assets/images/ic_chevron_right.png'),
  searchIcon: require('../assets/images/searchGlyph.png'),
  backArrow: require('../assets/images/back-arrow.png'),
  backArrow_white: require('../assets/images/back-arrow-white.png'),
  expand: require('../assets/images/expand.png'),
  check: require('../assets/images/check.png'),
  student: require('../assets/images/student.png'),
  tutor: require('../assets/images/tutor.png'),
  user: require('../assets/images/user.png'),
  book: require('../assets/images/book.png'),
  physics: require('../assets/images/physics.png'),
  beaker: require('../assets/images/beaker.png'),
  math: require('../assets/images/math.png'),
  civic: require('../assets/images/civic.png'),
  history: require('../assets/images/history.png'),
  geo: require('../assets/images/geo.png'),
  dna: require('../assets/images/dna.png'),
  kushal: require('../assets/images/kushal.png'),
  home: require('../assets/images/home.png'),
  home_active: require('../assets/images/home-active.png'),
  calendar: require('../assets/images/calendar.png'),
  calendar_icon: require('../assets/images/calendar-icon.png'),
  classes: require('../assets/images/classes.png'),
  tutor_tab: require('../assets/images/tutor_tab.png'),
  profile: require('../assets/images/profile.png'),
  cbse: require('../assets/images/cbse.png'),
  icse: require('../assets/images/icse.png'),
  ib: require('../assets/images/ib.png'),
  igcse: require('../assets/images/igcse.png'),
  heartFilled: require('../assets/images/heart-filled.png'),
  heart: require('../assets/images/heart.png'),
  bell: require('../assets/images/bell.png'),
  qpoint: require('../assets/images/qpoint.png'),
  cart: require('../assets/images/cart.png'),
  expand_gray: require('../assets/images/expand_grey.png'),
  collapse_grey: require('../assets/images/collapse_grey.png'),
  personal: require('../assets/images/personal.png'),
  parent_details: require('../assets/images/parent_details.png'),
  education: require('../assets/images/education.png'),
  cross: require('../assets/images/cross.png'),
  radio: require('../assets/images/radio.png'),
  calendar_active: require('../assets/images/calendar-active.png'),
  classes_active: require('../assets/images/classes-active.png'),
  tutor_active: require('../assets/images/tutor_active.png'),
  user_active: require('../assets/images/user_active.png'),
  profile_active: require('../assets/images/profile-active.png'),
  aboutGuru: require('../assets/images/about_guru.png'),
  bookingDetails: require('../assets/images/booking_details.png'),
  refFriend: require('../assets/images/referFriend.png'),
  myClass: require('../assets/images/my_class.png'),
  moreInformation: require('../assets/images/more_information.png'),
  logOut: require('../assets/images/log_out.png'),
  profile_footer_logo: require('../assets/images/guru_logo_profile_footer.png'),
  active_blue_circle: require('../assets/images/active_blue_circle.png'),
  small_active_blue: require('../assets/images/small_active_blue.png'),
  filter: require('../assets/images/filter.png'),
  radio_button_null: require('../assets/images/radio-button.png'),
  blue_star: require('../assets/images/blue_star.png'),
  grey_star: require('../assets/images/grey_star.png'),
  single_user: require('../assets/images/single_user.png'),
  multiple_user: require('../assets/images/multiple_user.png'),
  user_board: require('../assets/images/user_board.png'),
  blue_cross: require('../assets/images/blue_cross.png'),
  share: require('../assets/images/share.png'),
  four_stars: require('../assets/images/four_stars.png'),
  laptop: require('../assets/images/laptop.png'),
  settings: require('../assets/images/settings.png'),
  rectangle: require('../assets/images/rectangle.png'),
  dash_img: require('../assets/images/dash_img.png'),
  abroad: require('../assets/images/abroad.png'),
  pen_paper: require('../assets/images/pen_paper.png'),
  school_education: require('../assets/images/school_education.png'),
  language: require('../assets/images/language.png'),
  golden_star: require('../assets/images/golden_star.png'),
  understanding: require('../assets/images/understanding.png'),
  thumb_range: require('../assets/images/thumb_range.png'),
  stats: require('../assets/images/stats.png'),
  methodology: require('../assets/images/methodology.png'),
  professional: require('../assets/images/professional.png'),
  chat: require('../assets/images/chat.png'),
  minus_blue: require('../assets/images/minus_blue.png'),
  plus_blue: require('../assets/images/plus_blue.png'),
  logo_yellow: require('../assets/images/logo_yellow.png'),
  cart_white: require('../assets/images/cart_white.png'),
  white_plus_with_blue_back: require('../assets/images/white_plus_with_blue_back.png'),
  confirmed_booking: require('../assets/images/confirmed_booking.png'),
  thank_you: require('../assets/images/thank_you.png'),
  two_users: require('../assets/images/two_users.png'),
  attendees: require('../assets/images/attendees.png'),
  tutor_icon: require('../assets/images/tutor-icon.png'),
  pin: require('../assets/images/pin.png'),
  attachment: require('../assets/images/attachment.png'),
  video: require('../assets/images/video.png'),
  online_top_img: require('../assets/images/online_top_img.png'),
  online_right: require('../assets/images/online_right.png'),
  online_left: require('../assets/images/online_left.png'),
  selected_star: require('../assets/images/selected_star.png'),
  post_needs: require('../assets/images/post_needs.png'),
  refer_earn: require('../assets/images/refer_earn.png'),

  pdf: require('../assets/images/pdf.png'),
  png: require('../assets/images/png.png'),
  jpg: require('../assets/images/jpg.png'),
  txt: require('../assets/images/txt.png'),

  microphone: require('../assets/images/microphone.png'),
  microphone_mute: require('../assets/images/microphone-mute.png'),
  microphone_mute_white: require('../assets/images/microphone-mute-white.png'),
  phone: require('../assets/images/phone.png'),
  video_call: require('../assets/images/video-call.png'),
  video_call_mute: require('../assets/images/video-call-mute.png'),
  video_call_mute_white: require('../assets/images/video-call-mute-white.png'),
  camera_switch: require('../assets/images/camera-switch.png'),
  speaker: require('../assets/images/speaker.png'),
  speaker_enabled: require('../assets/images/speaker-enabled.png'),
  messaging_white: require('../assets/images/messaging-white.png'),
  share_screen: require('../assets/images/share-screen.png'),

  individual_class: require('../assets/images/individual-class.png'),
  group_class: require('../assets/images/group-class.png'),
  free_demo: require('../assets/images/free-demo.png'),
  online_class: require('../assets/images/online-class.png'),
  home_tuition: require('../assets/images/home-tuition.png'),
  individual_class_filled: require('../assets/images/individual-class-filled.png'),
  group_class_filled: require('../assets/images/group-class-filled.png'),
  free_demo_filled: require('../assets/images/free-demo-filled.png'),
  online_class_filled: require('../assets/images/online-class-filled.png'),
  home_tuition_filled: require('../assets/images/home-tuition-filled.png'),

  checkbox: require('../assets/images/checkbox.png'),
  checkbox_selected: require('../assets/images/checkbox-selected.png'),

  empty_cart: require('../assets/images/empty-cart.png'),
  empty_classes: require('../assets/images/no-classes.png'),
  empty_schedule: require('../assets/images/no-schedule.png'),
  star_half_orange: require('../assets/images/start-half-orange-o.png'),
  star_orange: require('../assets/images/star-orange.png'),
  star_unfilled: require('../assets/images/star-o.png'),

  vertical_dots: require('../assets/images/vertical-dots.png'),
  horizontal_dots: require('../assets/images/horizontal-dots.png'),

  arrow_down: require('../assets/images/arrow-down.png'),

  wallet_active: require('../assets/images/wallet-active.png'),
  wallet: require('../assets/images/wallet.png'),

  refer: require('../assets/images/refer.png'),
  refer_one: require('../assets/images/refer_one.png'),
  refer_two: require('../assets/images/refer_two.png'),
  refer_three: require('../assets/images/refer_three.png'),

  dash_tutor_img: require('../assets/images/dash_tutor_img.png'),
  student_requests: require('../assets/images/student_requests.png'),
  performance: require('../assets/images/performance.png'),
  b_star: require('../assets/images/b_star.png'),
  dots: require('../assets/images/dots.png'),
  bank: require('../assets/images/bank.png'),
};

export default Images;
