const Images = {
  onboarding1: require('../assets/images/tutorDetail5.png'),
  onboarding2: require('../assets/images/onboarding2.png'),
  onboarding3: require('../assets/images/onboarding3.png'),
  chevronRight: require('../assets/images/ic_chevron_right.png'),
  searchIcon: require('../assets/images/searchGlyph.png'),
  arrowRight: require('../assets/images/arrow-right.png'),
  expand: require('../assets/images/expand.png'),
  check: require('../assets/images/check.png'),
  student: require('../assets/images/student.png'),
  tutor: require('../assets/images/tutor.png'),
  user: require('../assets/images/user.png'),
  book: require('../assets/images/book.png'),
  physics: require('../assets/images/physics.png'),
  beaker: require('../assets/images/beaker.png'),
  math: require('../assets/images/math.png'),
  civic: require('../assets/images/civic.png'),
  history: require('../assets/images/history.png'),
  geo: require('../assets/images/geo.png'),
  dna: require('../assets/images/dna.png'),
  kushal: require('../assets/images/kushal.png'),
  home: require('../assets/images/home.png'),
  home_active: require('../assets/images/home_active.png'),
  calendar: require('../assets/images/calendar.png'),
  classes: require('../assets/images/classes.png'),
  tutor_tab: require('../assets/images/tutor_tab.png'),
  profile: require('../assets/images/profile.png'),
  cbse : require('../assets/images/cbse.png'),
  icse : require('../assets/images/icse.png'),
  ib : require('../assets/images/ib.png'),
  igcse : require('../assets/images/igcse.png'),
  heart : require('../assets/images/heart.png'),
  bell : require('../assets/images/bell.png'),
  qpoint : require('../assets/images/qpoint.png'),
  cart : require('../assets/images/cart.png'),
};

export default Images;
